name: 'Terraform Plan'
description: 'Reusable Action'
inputs:
  role_arn:
    required: true
  working_dir:
    required: true
  environment:
    required: true

runs:
  using: "composite"
jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{.inputs.role_arn }}
          role-session-name: github_action
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: make init ENV=${{ inputs.environment }}
        working-directory: ${{ inputs.working_dir }}

      - name: Terraform Validation
        id: validate
        run: terraform validate
        working-directory: ${{ inputs.working_dir }}

      - name: Terraform Plan
        id: plan
        run: make plan ENV=${{ inputs.environment }}
        working-directory: ${{ inputs.working_dir }}
